### ISSUE TITLE
Plot graphics is not working

### ISSUE THREAD

**Issue by filipesaraiva** [cokelaer/fitter#13]
I am getting errors related to plotting data. It is expected to `fitter` plot some graphics but it is not working. These are the message errors I am getting:

```
>>> f.fit()
Fitted norm distribution with error=0.26388354842966155)
Fitted expon distribution with error=0.21704685620029987)
>>> f.summary()
/usr/lib/python3.7/site-packages/matplotlib/axes/_axes.py:6521: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  alternative="'density'", removal="3.1")
       sumsquare_error
expon         0.217047
norm          0.263884
>>> f.hist()
/usr/lib/python3.7/site-packages/matplotlib/axes/_axes.py:6521: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  alternative="'density'", removal="3.1")
```

Looks like they are just warnings, not errors itself, but the plotting is not working anyway. Any idea?

**Comment by cokelaer** [comment]
I believe the deprecated warnings are not in fitter but in matplotlib library itself. Although it may be because of an older version of fitter; Which version do you use ?

As for the plotting, there is no error so I believe this is a common issue in matplotlib where your backend is not set properly. 

Check your backend:

    import matplotlib
    matplotlib.get_backend()

you may get Agg, Qt, etc. You can change it and try other backend (e.g Qt). Please do check the matplotlib document. Another way is to start ipython shell with the --pylab option. This may help. Finally, to change the backend permanently, you can create a "matplotlib" file in your home; This those things change quite quickly, check out the matplotlib documentation.

**Comment by nily-dti** [comment]
It does not work to change matplotlib backend. I've tried: `'GTK3Agg', 'Qt4Agg', 'Qt5Agg', 'TkAgg', 'WX', 'WXAgg',`

**Comment by victorfig** [comment]
A quick fix for me was to add the following lines after `f.hist()`:
```
import matplotlib.pyplot as plt
plt.show()

```
