### ISSUE TITLE
Adding an option for the density (normalisation)

### ISSUE THREAD

**Issue by Hosein47** [cokelaer/fitter#22]
Is it possible to add an option to have a fit (including the fit parameters) for "density=False"? And in the end, have a choice when calling an object from Fitter?

**Comment by cokelaer** [comment]
Unfortunately, at the moment the fitting is performed on the normalised distribution ( the probability density function ) because the functions to fit are the PDF from scipy. So, I do not see any way to do it differently at the moment. I'll be happy to accept a PR if you find a solution. In the new version 1.2, the attribute `_density` has been added. It is used in the plotting and if set to False, the data with notbe pre-treated with density=True. However, fitting and final plotting will not be relevant. I implemented this feature in case one finds a solution.
